{
  "resourceType": "ValueSet",
  "id": "2.16.840.1.113762.1.4.1029.373",
  "url": "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1029.373",
  "identifier": [ {
    "system": "urn:ietf:rfc:3986",
    "value": "2.16.840.1.113762.1.4.1029.373"
  } ],
  "version": "20220127",
  "name": "COVID19Confirmed",
  "title": "COVID 19 Confirmed",
  "status": "active",
  "experimental": false,
  "publisher": "NLM",
  "expansion": {
    "identifier": "20240502",
    "timestamp": "2025-01-10T13:55:12-07:00",
    "contains": [ {
      "system": "http://hl7.org/fhir/sid/icd-10-cm",
      "version": "2024",
      "code": "B97.29",
      "display": "Other coronavirus as the cause of diseases classified elsewhere"
    }, {
      "system": "http://hl7.org/fhir/sid/icd-10-cm",
      "version": "2024",
      "code": "J12.82",
      "display": "Pneumonia due to coronavirus disease 2019"
    }, {
      "system": "http://hl7.org/fhir/sid/icd-10-cm",
      "version": "2024",
      "code": "U07.1",
      "display": "COVID-19"
    }, {
      "system": "http://snomed.info/sct",
      "version": "2023-09",
      "code": "840539006",
      "display": "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
    } ]
  }
}